@startuml
left to right direction

actor "Pengguna" as Pengguna

package "Sistem Manajemen Haji" {
    ' Authentication
    usecase "Login" as UC1
    usecase "Daftar" as UC2
    usecase "masukan email"as UC31
    usecase "masukan password" as UC32

    ' Dashboard
    usecase "Lihat Dashboard" as UC3

    ' View Jamaah Data
    usecase "Lihat Profil Jamaah" as UC8

    ' View Other Data
    usecase "Lihat Pembimbing" as UC24
    usecase "Lihat Berita" as UC25
    usecase "Lihat Panduan Daftar" as UC26
    usecase "Lihat Status" as UC27

    ' Profile Management
    usecase "Lihat Profil Pengguna" as UC28
    usecase "Edit Profil Pengguna" as UC29
    usecase "Ubah Password" as UC30

    ' Includes
    UC3 ..> UC1 : include
    UC8 ..> UC1 : include
    UC24 ..> UC1 : include
    UC25 ..> UC1 : include
    UC26 ..> UC1 : include
    UC27 ..> UC1 : include
    UC28 ..> UC1 : include
    UC29 ..> UC1 : include
    UC30 ..> UC1 : include
    UC1 ..> UC2 : include
}

'
' Pengguna relations
'
UC31 --> UC2 
UC32 --> UC2 
Pengguna --> UC3
Pengguna --> UC8
Pengguna --> UC24
Pengguna --> UC25
Pengguna --> UC26
Pengguna --> UC27
Pengguna --> UC28
Pengguna --> UC29
Pengguna --> UC30

@enduml
