@startuml Sequence Diagram - Sistem Informasi Jamaah Haji (1/4)

actor Admin
actor User
participant Browser
participant Server
participant DB

== Login ==
Admin -> Browser: Login
Browser -> Server: POST login
Server -> DB: Query
DB -> Server: Data
Server -> Browser: Dashboard

User -> Browser: Login
Browser -> Server: POST login
Server -> DB: Query
DB -> Server: Data
Server -> Browser: Dashboard

== Dashboard ==
Admin -> Browser: Dashboard
Browser -> Server: GET
Server -> DB: Count
DB -> Server: Count
Server -> Browser: Page

User -> Browser: Dashboard
Browser -> Server: GET
Server -> DB: Count
DB -> Server: Count
Server -> Browser: Page

@enduml
