<?php
require 'vendor/autoload.php';

$dompdf = new Dompdf\Dompdf();
$dompdf->loadHtml('<h1>Test PDF</h1><p>This is a test PDF generated by Dompdf.</p>');
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('test.pdf');
?>
